In [2]:
import pandas as pd

In [16]:
df = pd.read_csv('example-data-test.csv')

In [17]:
df

,CustomerID,Gender,SeniorCitizen,Age,Married,City,Country,ZipCode,Population,Latitude,...,TotalExtraDataCharges,TotalLongDistanceCharges,TotalRefunds,TotalRevenue,AvgMonthlyGBDownload,AvgMonthlyLongDistanceCharges,ChurnCategory,ChurnReason,ChurnScore,CLTV
0,7591-VHVEG,Male,0,42,Yes,San Francisco,United States,94102,88452.0,37.7794,...,0.0,45.0,0.00,1124.40,25.00,3.75,NaN,NaN,35.0,4875.0
1,5576-GNVDE,Female,0,35,No,Los Angeles,United States,90012,30596.0,34.0659,...,0.0,120.5,0.00,1487.30,18.00,5.02,NaN,NaN,42.0,3982.0
2,3669-QPYBK,Male,0,28,No,San Diego,United States,92101,27505.0,32.7157,...,0.0,15.6,0.00,255.30,35.00,5.2,NaN,NaN,68.0,3129.0
3,7796-CFOCW,Female,0,51,Yes,Sacramento,United States,95814,47800.0,38.5816,...,0.0,0.0,0.00,1629.00,12.00,0.0,NaN,NaN,28.0,4521.0
4,9238-HQITU,Male,0,22,No,San Jose,United States,95112,58200.0,37.3387,...,0.0,85.3,0.00,882.50,28.00,10.66,NaN,NaN,55.0,5231.0
5,9306-CDSKC,Female,0,39,Yes,Long Beach,United States,90805,91664.0,33.8541,...,0.0,225.6,0.00,1124.10,22.00,15.04,NaN,NaN,37.0,3874.0
6,1453-KIOVK,Male,0,47,No,Oakland,United States,94601,42900.0,37.7805,...,0.0,420.5,0.00,3004.40,45.00,14.5,NaN,NaN,62.0,4782.0
7,6714-OKOMC,Female,0,31,No,Fresno,United States,93721,55200.0,36.7468,...,0.0,0.0,0.00,277.55,10.00,0.0,NaN,NaN,45.0,2987.0
8,7893-POOKP,Male,0,25,Yes,Anaheim,United States,92801,35200.0,33.8366,...,0.0,185.4,0.00,2491.00,38.00,8.43,NaN,NaN,51.0,5123.0
9,6389-TABGU,Female,0,58,No,Santa Ana,United States,92701,33400.0,33.7456,...,0.0,310.8,0.00,3006.00,15.00,6.48,NaN,NaN,33.0,4215.0
10,9764-GRSKD,Male,0,33,Yes,Riverside,United States,92501,32400.0,33.9806,...,50.0,180.2,0.00,929.50,20.00,12.87,NaN,NaN,59.0,3562.0
11,7470-LKBCI,Female,0,45,No,Bakersfield,United States,93301,38000.0,35.3733,...,210.4,0.0,570.45,0.00,11.07,NaN,NaN,41,4873.0,NaN
12,8092-TTVAX,Male,0,36,Yes,Stockton,United States,95202,31100.0,37.9577,...,0.0,195.6,0.00,4410.30,12.00,4.66,NaN,NaN,47.0,5432.0
13,0281-XJGEX,Female,0,29,No,Chula Vista,United States,91910,74025.0,32.6368,...,0.0,1875.3,0.00,6541.80,14.00,41.67,NaN,NaN,72.0,5783.0
14,5130-JLPIS,Male,0,52,Yes,Irvine,United States,92618,45200.0,33.6846,...,0.0,260.0,0.00,3108.50,43.00,9.63,NaN,NaN,38.0,4987.0
15,3656-SNQYZ,Female,0,44,No,Modesto,United States,95350,21400.0,37.6391,...,0.0,1950.6,0.00,9085.35,8.00,30.96,NaN,NaN,54.0,6124.0
16,8192-XWSZG,Male,0,57,No,Oxnard,United States,93030,20700.0,34.1975,...,980.4,0.0,2033.55,0.00,19.22,NaN,NaN,39,5216.0,NaN
17,9960-WOFKT,Female,0,62,Yes,Fontana,United States,92335,21200.0,34.0922,...,0.0,950.4,0.00,8207.00,9.00,13.98,NaN,NaN,43.0,4479.0
18,4191-MFLUW,Male,0,23,No,Moreno Valley,United States,92553,20800.0,33.9375,...,0.0,42.5,0.00,152.90,65.00,21.25,NaN,NaN,57.0,5925.0
19,4184-MYFRB,Female,0,37,Yes,Glendale,United States,91201,23981.0,34.1705,...,30.0,125.6,0.00,1956.60,70.00,6.28,NaN,NaN,58.0,5982.0
20,8780-QRDMV,Male,1,65,No,Huntington Beach,United States,92646,19800.0,33.6784,...,20.0,0.0,0.00,59.65,8.00,0.0,Competitor,Competitor offered more data,91.0,5433.0
21,1681-VDCWW,Female,0,48,Yes,Garden Grove,United States,92840,17600.0,33.7743,...,110.4,0.0,328.20,0.00,10.04,NaN,NaN,77,5279.0,NaN
22,1067-JKSGK,Male,0,30,No,Oceanside,United States,92056,52895.0,33.1947,...,28.3,0.0,48.45,0.00,28.30,Competitor,Competitor made better offer,92,4832.0,NaN
23,3639-WEABW,Female,0,26,Yes,Santa Clarita,United States,91350,40077.0,34.5024,...,0.0,2650.8,0.00,5945.30,72.00,48.2,NaN,NaN,53.0,6407.0
24,6323-HRPFA,Male,0,43,Yes,Pomona,United States,91766,36057.0,34.0679,...,0.0,240.5,0.00,2982.10,28.00,5.23,NaN,NaN,79.0,4986.0
25,6866-JZNKO,Female,0,26,No,Torrance,United States,90503,41979.0,33.8404,...,0.0,550.8,0.00,2099.20,25.00,19.67,NaN,NaN,65.0,2725.0
26,6468-CHFZW,Male,0,59,Yes,Pasadena,United States,91101,16812.0,34.1466,...,0.0,1380.6,0.00,5752.00,15.00,31.38,Competitor,Competitor had better devices,77.0,5789.0
27,8666-UTDHZ,Male,0,28,Yes,Escondido,United States,92025,49281.0,33.0815,...,0.0,0.0,0.00,30.20,55.00,0.0,Competitor,Competitor had better devices,90.0,2915.0
28,5249-YGIJN,Male,0,37,Yes,Sunnyvale,United States,94085,58000.0,37.3688,...,0.0,750.6,0.00,6977.85,25.00,10.88,NaN,NaN,21.0,5974.0
29,8774-HHUOZ,Female,0,21,No,Concord,United States,94520,12900.0,37.9780,...,0.0,670.5,0.00,1705.70,38.00,41.91,Competitor,Competitor offered higher download speeds,74.0,3022.0
30,3842-NFECX,Male,1,68,Yes,Corona,United States,92879,16800.0,33.8753,...,0.0,3250.5,0.00,9802.30,10.00,47.8,NaN,NaN,38.0,5309.0
31,4930-XIHVW,Female,1,72,Yes,Lancaster,United States,93534,16100.0,34.6868,...,10.0,60.5,0.00,261.50,9.00,30.25,NaN,NaN,69.0,4449.0
32,6828-IEAUQ,Female,0,47,Yes,Palmdale,United States,93550,15400.0,34.5794,...,0.0,1050.8,0.00,2704.55,11.00,42.03,NaN,NaN,66.0,3213.0
33,7311-EGVHZ,Male,0,36,No,Salinas,United States,93901,15500.0,36.6777,...,20.8,0.0,41.00,0.00,20.80,NaN,NaN,77,5526.0,NaN
34,3414-BMNZE,Male,1,70,No,Hayward,United States,945,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
print(df.dtypes)

CustomerID                        object
Gender                            object
SeniorCitizen                      int64
Age                                int64
Married                           object
City                              object
Country                           object
ZipCode                            int64
Population                       float64
Latitude                         float64
Longitude                        float64
Partner                           object
Dependents                        object
PhoneService                      object
MultipleLines                     object
InternetService                   object
StreamingTV                       object
StreamingMovies                   object
StreamingMusic                    object
UnlimitedData                     object
Contract                          object
PaperlessBilling                  object
PaymentMethod                     object
OnlineSecurity                    object
OnlineBackup                      object
DeviceProtection                  object
TechSupport                       object
Referrals                         object
ReferredFriend                    object
SatisfactionScore                float64
Tenure                           float64
MonthlyCharges                   float64
TotalCharges                     float64
TotalExtraDataCharges            float64
TotalLongDistanceCharges         float64
TotalRefunds                     float64
TotalRevenue                     float64
AvgMonthlyGBDownload             float64
AvgMonthlyLongDistanceCharges     object
ChurnCategory                     object
ChurnReason                       object
ChurnScore                       float64
CLTV                             float64
dtype: object

In [12]:
df.dropna(inplace=True,axis=1)

In [13]:
df.isna().count()

CustomerID                       4
Gender                           4
SeniorCitizen                    4
Age                              4
Married                          4
City                             4
Country                          4
ZipCode                          4
Population                       4
Latitude                         4
Longitude                        4
Partner                          4
Dependents                       4
PhoneService                     4
MultipleLines                    4
InternetService                  4
StreamingTV                      4
StreamingMovies                  4
StreamingMusic                   4
UnlimitedData                    4
Contract                         4
PaperlessBilling                 4
PaymentMethod                    4
OnlineSecurity                   4
OnlineBackup                     4
DeviceProtection                 4
TechSupport                      4
Referrals                        4
ReferredFriend                   4
SatisfactionScore                4
Tenure                           4
MonthlyCharges                   4
TotalCharges                     4
TotalExtraDataCharges            4
TotalLongDistanceCharges         4
TotalRefunds                     4
TotalRevenue                     4
AvgMonthlyGBDownload             4
AvgMonthlyLongDistanceCharges    4
ChurnCategory                    4
ChurnReason                      4
ChurnScore                       4
CLTV                             4
dtype: int64

In [ ]:
df_clean= df.drop(columns=['CustomerID','Latitude', 'Longitude', 'ZipCode','City','ChurnCategory','ChurnReason', 'ChurnScore', 'Country', 'ReferredFriend'],axis=1)

In [14]:
df = df.dropna()

In [15]:
df

,CustomerID,Gender,SeniorCitizen,Age,Married,City,Country,ZipCode,Population,Latitude,...,TotalExtraDataCharges,TotalLongDistanceCharges,TotalRefunds,TotalRevenue,AvgMonthlyGBDownload,AvgMonthlyLongDistanceCharges,ChurnCategory,ChurnReason,ChurnScore,CLTV
20,8780-QRDMV,Male,1,65,No,Huntington Beach,United States,92646,19800.0,33.6784,...,20.0,0.0,0.0,59.65,8.0,0.0,Competitor,Competitor offered more data,91.0,5433.0
26,6468-CHFZW,Male,0,59,Yes,Pasadena,United States,91101,16812.0,34.1466,...,0.0,1380.6,0.0,5752.00,15.0,31.38,Competitor,Competitor had better devices,77.0,5789.0
27,8666-UTDHZ,Male,0,28,Yes,Escondido,United States,92025,49281.0,33.0815,...,0.0,0.0,0.0,30.20,55.0,0.0,Competitor,Competitor had better devices,90.0,2915.0
29,8774-HHUOZ,Female,0,21,No,Concord,United States,94520,12900.0,37.9780,...,0.0,670.5,0.0,1705.70,38.0,41.91,Competitor,Competitor offered higher download speeds,74.0,3022.0